# Generated by Django 4.1.13 on 2024-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.IntegerField(default=999),
        ),
    ]
